### PR TITLE
Dutch translation

### PR DESCRIPTION
**Pull request by Willem3141**
@M1dgard There we go!
- [x] Banner
- [x] Title
- [x] Page 1 (Digging)
- [x] Page 2 (Mother Nature)
- [x] Page 3 (Idea)
- [x] Page 4 (Poetry)
- [x] Page 5 (Inappropriate)
- [x] Page 6 (Guitar)
- [x] Page 7 (New rules)

I am currently travelling, so I'll respond a little slower than usual maybe... If you don't beat me to it, I'll try to do a first version of the translation tonight :smile:

### CODE REVIEW

**Comment by Willem3141** [comment]
I made a first pass and translated everything. However, I am not really happy about quite a few of the lines; it just doesn't ‘flow’ nicely. Feel free to modify anything :smile: 

In particular, let's collaborate on Cayenne's poem!

> Oh, beau guerrier blond aux cheveux d'or!
> Toi qui hantes mon chaos!
> Tu es l'entropie de mes aurores.

My version:

> O, schone blonde krijger, met je gulden haar!
> Jij die rondspookt in mijn chaos!
> Je bent de entropie van mijn noorderlicht.

It seems that any poetry sounds better in French :wink:

**Comment by Willem3141** [comment]
By the way, @M1dgard, do you think it would be good to translate the names of the witches of Chaosah? Those spices have Dutch names, and since we also translated Saffron -> Saffraan and Coriander -> Koriander, it seems to make sense to translate them too. For example:
- Cumin -> [Komijn](https://nl.wikipedia.org/wiki/Komijn)
- Thym -> [Tijm](https://nl.wikipedia.org/wiki/Tijm)
- Cayenne can stay [Cayenne](https://nl.wikipedia.org/wiki/Cayennepeper)

This of course would need to be done consistently in all episodes where their names are mentioned (11, 14, 15, 16, 18, 19).

On the other hand, we did not translate Pepper (-> Peper / Paprika?) and Carrot (-> Wortel?), and I don't think we should. So we are inconsistent anyway :smile: 

I filled out the current Dutch translations [here](https://docs.google.com/spreadsheets/d/1zRqVAj8q1iHwOXQBplXp_DaoZyDgJ3uA0_st_iZEDGg/edit#gid=0).

**Comment by Willem3141** [comment]
@M1dgard, did you maybe miss this? :smiley: 

I'll make a final version (mainly resizing text balloons) tomorrow.

**Comment by Willem3141** [comment]
I am happy with the translation now :tada:

**Comment by ghost** [comment]
@Willem3141 wrote:

> @M1dgard, did you maybe miss this? 😃

I saw it in my emails, but I'm super busy lately, sorry! I hope I can help for the next episode, and I'll check this translation when if have the time.

**Comment by Willem3141** [comment]
No problem!

**Pull request merged**
